# Generated by Django 5.2.3 on 2025-11-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogrenci_no', models.CharField(max_length=20, unique=True, verbose_name='Öğrenci No')),
                ('isim', models.CharField(max_length=50, verbose_name='İsim')),
                ('soyisim', models.CharField(max_length=50, verbose_name='Soyisim')),
                ('tekno_s1', models.IntegerField(verbose_name='Kodlama/Yazılım İlgisi (1-5)')),
                ('tekno_s2', models.IntegerField(verbose_name='Robotik/Mekanik İlgisi (1-5)')),
                ('el_s1', models.IntegerField(verbose_name='İnce İşçilik/Maket İlgisi (1-5)')),
                ('el_s2', models.IntegerField(verbose_name='Düğüm/El Sanatları İlgisi (1-5)')),
                ('dil_s1', models.IntegerField(verbose_name='Yabancı Dil Öğrenme İsteği (1-5)')),
                ('dil_s2', models.IntegerField(verbose_name='Farklı Kültürlere Merak (1-5)')),
                ('strat_s1', models.IntegerField(verbose_name='Zeka Oyunları İlgisi (1-5)')),
                ('strat_s2', models.IntegerField(verbose_name='Planlama/Analiz Yeteneği (1-5)')),
                ('sanat_s1', models.IntegerField(verbose_name='Müzik/Enstrüman İlgisi (1-5)')),
                ('sanat_s2', models.IntegerField(verbose_name='Görsel Sanatlar/Fotoğraf İlgisi (1-5)')),
                ('sertifika', models.FileField(blank=True, null=True, upload_to='belgeler/', verbose_name='Sertifika')),
                ('tahmin_edilen_kulup', models.CharField(blank=True, choices=[('Yapay Zeka', 'Yapay Zeka Kulübü'), ('Robotik', 'Robotik ve Mekatronik'), ('Yabancı Dil', 'Yabancı Dil'), ('Gemi Bağları', 'Gemi Bağları'), ('Gemi Model', 'Gemi Maket Modelciliği'), ('Satranç', 'Satranç'), ('El Sanatları', 'El Sanatları'), ('Müzik', 'Müzik'), ('Fotoğrafçılık', 'Fotoğrafçılık')], max_length=50)),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
